# Generated by Django 3.2.5 on 2021-07-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='название')),
                ('user_phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('user_email', models.CharField(max_length=50, verbose_name='адрес')),
                ('order_date', models.DateField(verbose_name='дата')),
                ('description', models.TextField(verbose_name='описание')),
            ],
        ),
    ]
